# Default values for kube-native.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: gcr.io/shanesveller-1147/kube_native
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kube-native.sveller.codes

ingress:
  enabled: false
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: google-dns-production
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - kube-native.sveller.codes
  tls:
   - secretName: wildcard-sveller-codes
     hosts:
       - sveller.codes
       - '*.sveller.codes'

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
# affinity:
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: app.kubernetes.io/name
#           operator: In
#           values:
#           - kube-native
#       topologyKey: kubernetes.io/hostname


deployment:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate

node_cookie: hunter2
secrets_exs: |
  use Mix.Config

  config :kube_native, KubeNative.Repo,
    url:
      "ecto://kube-native:kube-native@kube-native-postgresql.default.svc.cluster.local/kube-native"

  config :kube_native_web, KubeNativeWeb.Endpoint,
    force_ssl: [hsts: false, expires: 3600, exclude: nil],
    http: [:inet6, port: 4000],
    https: [
      :inet6,
      port: 4001,
      cipher_suite: :strong,
      keyfile: "/app/tls/tls.key",
      certfile: "/app/tls/tls.crt"
    ],
    url: [host: "kube-native.sveller.codes", port: 443]

tls:
  secret:
    name: wildcard-sveller-codes
    key_filename: tls.key
    cert_filename: tls.crt
