apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-native.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-native.name" . }}
    helm.sh/chart: {{ include "kube-native.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
