apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kube-native.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "kube-native.name" . }}
    helm.sh/chart: {{ include "kube-native.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "kube-native.name" . }}
        helm.sh/chart: {{ include "kube-native.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ template "kube-native.fullname" . }}
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate", ""] # TODO: arity 0 version?
          env:
            - name: "NODE_COOKIE"
              valueFrom:
                secretKeyRef:
                  key: node_cookie
                  name: {{ template "kube-native.fullname" . }}
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "REPLACE_OS_VARS" # TODO: Conditional by Value
              value: "true"
          ports: []
          volumeMounts: # TODO
            # - name: app-config
            #   mountPath: /app/etc/config.exs
            #   readOnly: true
            #   subPath: config.exs
            - name: app-secrets
              mountPath: /app/etc/config.exs
              readOnly: true
              subPath: secrets.exs
            # - name: app-tls
            #   mountPath: /app/tls
            #   readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      # TODO
      volumes:
        - name: app-config
          configMap:
            name: {{ template "kube-native.fullname" . }}
            items:
              - key: config.exs
                path: config.exs
        - name: app-secrets
          secret:
            secretName: {{ template "kube-native.fullname" . }}
            items:
              - key: secrets.exs
                path: secrets.exs
        # - name: app-tls
        #   secret:
        #     secretName: {{ .Values.tls.secret.name }}
        #     items:
        #       - key: {{ .Values.tls.secret.key_filename }}
        #         path: {{ .Values.tls.secret.key_filename }}
        #       - key: {{ .Values.tls.secret.cert_filename }}
        #         path: {{ .Values.tls.secret.cert_filename }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
