apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-native-env
  labels:
    app: kube-native
data:
  HOSTNAME: localhost
  PORT: "4000"
  # cannot be a YAML boolean true, thus the quotes
  REPLACE_OS_VARS: "true"
