apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-native
  labels:
    app: kube-native
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-native
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-native
    spec:
      containers:
        - name: kube-native
          image: kube-native:latest
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: kube-native-env
            - secretRef:
                name: kube-native-env-secret
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          # TODO: handle non-zero exit on normal command behavior
          # lifecycle:
          #   preStop:
          #     exec:
          #       command:
          #         - /app/bin/ex_mud
          #         - stop
          livenessProbe:
            exec:
              command:
                - /app/bin/kube_native_umbrella
                - ping
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
