apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kube-native-env-secret
  labels:
    app: kube-native
data:
  # echo -n "string" | base64
  # ecto://kube_native:kube_native@kube-native-postgresql.kube-native.svc.cluster.local/kube_native
  DATABASE_URL: ZWN0bzovL2t1YmVfbmF0aXZlOmt1YmVfbmF0aXZlQGt1YmUtbmF0aXZlLXBvc3RncmVzcWwua3ViZS1uYXRpdmUuc3ZjLmNsdXN0ZXIubG9jYWwva3ViZV9uYXRpdmU=
  # "cookie"
  ERLANG_COOKIE: Y29va2ll
  # value from docker-compose.yml
  SECRET_KEY_BASE: ZnpCazhPRWNJOHRoR3hseXBXUFVxZlIydzJXb3BkTjh2OHBtcHV5MkpOajJlZXJiWUZubGVjdVZNckZQR1luVw==
