apiVersion: v1
kind: Service
metadata:
  name: kube-native
  labels:
    app: kube-native
spec:
  type: NodePort # LoadBalancer, NodePort, ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kube-native
